name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  publish:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      env:
        API_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Pack
      run: |
        cd ./src/EndpointsMapper
        dotnet pack -c Release -o out
    - name: Publish
      run: dotnet nuget push ./src/EndpointsMapper/out/*.nupkg --api-key {API_KEY} --source https://api.nuget.org/v3/index.json
    
